### ISSUE TITLE
Problems running Daxif script in Visual studio 2017 v15.3 and up

### ISSUE THREAD

**Issue by TomMalow** [delegateas/Daxif#14]
Some Daxif f# scripts fails when running in F# interactive in Visual Studio 2017 v15.3 and newer. The scripts fails due to Visual Studio trying to access two dll assemblies, Microsoft.VisualStudio.Shell.15.0.dll and Microsoft.VisualStudio.Shell.Framework.dll, which it cannot find. This is most likely an issue in the F# interactive in visual studio in cooperation with the CRM sdk assemblies.

The current solutions is to copy these two dll's into the same folder as the f# scripts.

The dll's can be found in the folder: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies

**Comment by henrikhannemose** [comment]
After updating to to Visual Studio 15.5 it is no longer necessary to use this hack.
