### ISSUE TITLE
Add handling of Entity/Attribute Mappings

### ISSUE THREAD

**Issue by TomMalow** [delegateas/Daxif#15]
Deletion of Attribute Mapping is not currently part of the solution and needs to be update for each environment. Additionally, it is know that upgrading an environment can result in deleted mappings being reintroduced. 

So two new things needs to be added to Daxif.

1.  Add methods for deleting and adding attribute mappings for a given environment (should always be dev) given a list of mappings.
2.  Add Attribute Mappings to Extended Solution so that it becomes part of the deploy process and synced across environments

**Comment by mlRosenquist** [comment]
@TomMalow I've looked into including 1. 
Regarding 2. do you remember if you had any thoughts on how to include it in the Extended Solution.
