### ISSUE TITLE
Change Extended Solution to delete plugin steps before the standard solution import

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/Daxif#29]
When renaming/deleting plugin steps in the source environment we are unable to import to the target environment. We get the error:

> Plug-in assembly does not contain the required types or assembly content cannot be updated

This makes sense, since the renamed/deleted plugin steps still exist in the target environment, but not in the updated assembly.

To work around this, our current best practice for years has been to delete all plugin steps in the target environment before importing.

[Extended Solution](https://github.com/delegateas/Daxif/wiki/Extended-Solution) stores information about the plugin steps in the source environment, but currently is only run after the standard solution import. I suggest changing Extended Solution such that it deletes plugin steps (that have been renamed/removed) before the standard solution import. In this way it would no longer be necessary to blindly delete all plugin steps before an import.

**Comment by TomMalow** [comment]
In this process i suggest to refactor Import to be a bit more modular. ex. `Import` module also handles publish if the imported solution was a unmanaged, then import publish it has part of it code. Import should instead return a status of the import and if it succeeded, then perform a publish. So extended import steps are:

- Delete plugin action from Extended Solution 
- Import
- Publish if managed
- Remaining Delete action from Extended Solution

**Comment by magesoe** [comment]
Added in 4.5.6
