### ISSUE TITLE
Add the ability to determine isolationmode in workflow

### ISSUE THREAD

**Issue by ferodom** [delegateas/Daxif#32]
When registering a workflow it would be nice to be able to select the isolationmode just like in the plugin.

I already made this change and I would like to submit a pull request.

**Comment by ferodom** [comment]
@magesoe are you taking pull requests?

**Comment by magesoe** [comment]
We love pull requests

**Comment by ferodom** [comment]
I tried making one but I am unauthorized. also which branch should I make the request to?

**Comment by magesoe** [comment]
You should be able to make a pull request, otherwise fork and make a pull request from your fork. Just make the pull request to the main branch

**Comment by magesoe** [comment]
Fixed by #34 and added in version 4.2.7
