### ISSUE TITLE
 Unable to generate context files: Invalid type for alternate key: OptionSet "Team_MembershipType"

### ISSUE THREAD

**Issue by danafal** [delegateas/Daxif#47]
**Describe the bug**
I have solution in Dynamics, where I used for generating the C Sharp Context, and executing the script for that, I have just added entity Team to the solution because I want to create plugin on Teams, and while generating the CSharp Context, i got an error "Unable to generate context files: Invalid type for alternate key: OptionSet "Team_MembershipType"

When I look at Dynamics the solution, fair enough, there are a manged solution from Microsoft, where there is an alternativ-key, that I cannot do much about it. I see this error as a bug, is it somthing you guys can confirm?

**To Reproduce**
1. Go to Dynamics, and make a solution include Entity Team in it.
2. Click on Visual Studio, and modify Script in Daxif folder GenerateCSharpContext.fsx and provide solution name created at point 1.
3. Run the modified script GenerateCSharpContext.fsx
4. See error at F# Interactive

**Expected behavior**
Here you will se an error simlar to the following:

(2020-10-13 09:22:54Z) [Error]: Unable to generate context files: Invalid type for alternate key: OptionSet "Team_MembershipType"

System.Exception: DG XrmContext failed
   at DG.Daxif.Common.Utility.postProcess(Int32 code, String es, String os, ConsoleLogger log, String proc) in ..\Daxif\src\Delegate.Daxif\Common\Utility.fs:line 173
   at DG.Daxif.Modules.Solution.Main.updateCustomServiceContext(Environment env, String outputDirectory, String pathToExe, LogLevel log, FSharpList`1 solutions, FSharpList`1 entities, FSharpList`1 extraArgs) in ..\Daxif\src\Delegate.Daxif\Modules\Solution\Main.fs:line 312
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in ..\Scripts\Daxif\GenerateCSharpContext.fsx:line 11
Stopped due to error

**Screenshots**
No need

**Environment**
- CRM/D365/CDS version: Crm Online v.(9.1.0.23470) (<instancename>.crm4.dynamics.com)
- Tool version: DAXIF# v.4.8.1.0
- Other applicable environments (Visual Studio Community 2019)

**Additional context**
No need

**Comment by magesoe** [comment]
Upgrade your version of XrmContext

**Comment by danafal** [comment]
> Upgrade your version of XrmContext

Thanks that helped. It works now.
