### ISSUE TITLE
Can you sync resx web resources with daxif?

### ISSUE THREAD

**Issue by mVermaat** [delegateas/Daxif#58]
I tried [syncing WebResources](https://github.com/delegateas/Daxif/wiki/WebResouresSyncDev), but it doesn't seem to synchronize web resources of type resx. Is that not supported or am I doing something wrong? The resx files are directly in the webresource folder.

**Comment by skovlund** [comment]
The list of web resource types that are synced can be found [here](https://github.com/delegateas/Daxif/blob/master/src/Delegate.Daxif/Daxif.fs) and has not yet been updated with .resx files. So they are not synced but should probably be.
