### ISSUE TITLE
SolutionExtract

### ISSUE THREAD

**Issue by CrmDev23** [delegateas/Daxif#8]
Hey guys
Awesome work! I just tried out the sample scripts, which worked perfectly fine. Although when I start the "SolutionExtract.fsx" from the console, it does nothing and the console stays empty.
Did I miss something?
Thanks

**Comment by henrikhannemose** [comment]
You are right that this script does not currently work. 
It appears that some refactoring has broken this part of the tooling (which we do not heavily utilize ourselves). 

Thanks for opening this issue. We will update it when there is an update available.
